FROM node:20-alpine AS build
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client/ .
ARG VITE_API_URL=https://vps-8aae2664.vps.ovh.net/api
ENV VITE_API_URL=$VITE_API_URL
ARG VITE_MAPTILER_KEY
ENV VITE_MAPTILER_KEY=$VITE_MAPTILER_KEY
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/venuewar.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
